print("Exercise 1: c) Store information for the long term")
print("Exercise 2: It is a sequence of instructions translated for the CPU")
print("Exercise 3: a compiler translates High level programming language to low level programming language and a")
print("interpreter translates program code to machine code one line at once")
print("Exercise 4: c) Python source file")
print("Exercise 5: spelling error, the word print")
print("Exercise 6: b) main memory")
print("Exercise 7: b) 44")
print("Exercise 8: 1) Maybe like a brain that only can make inputs and outputs")
print("2) Big brain with the stored memories")
print("3) Small brain with the sort memory")
print("4) eyes, nose")
print("5) fingers, toes")
print("Exercise 9: You check your code again for spelling errors")
